### ISSUE TITLE
cannot change background-color

### ISSUE THREAD

**Issue by t-cool** [t-cool/nantango#1]
I'm trying to write the function "answerIsWrong" that make the correct choice's color lightblue when the answer is wrong. 

When I execute "document.getElementById("A").style.backgroundColor = "lightblue" " on browser's console, it changes the color, but it doesn't work in the function answerIsWrong.

**Comment by t-cool** [comment]
updated

**Comment by shahrukh170** [comment]
Try this for multiple CSS styles:

$(this).css({
    "background-color": 'red',
    "color" : "white"
});

**Comment by moazzamhossain7** [comment]
Try this:

document.getElementById("A").style.backgroundColor = "lightblue !important"

**Comment by shahrukh170** [comment]
3 options:

Move the JavaScript under the div so that computer can find the div A in your code first then Use window.onload in your JavaScript

**Comment by t-cool** [comment]
@moazzamhossain7 
@shahrukh170 

Thank you for your advice.

So far, I use the way as @moazzamhossain7  proposed.
> document.getElementById("A").style.backgroundColor = "lightblue";

It works on console of the browser, but it doesn't work through loading `quiz.js`.

```
function colorA(){
    document.getElementById("A").style.backgroundColor = "lightblue";
    sleep(3000);
}

function colorB(){
    document.getElementById("B").style.backgroundColor = "lightblue";
    sleep(3000);
}

function colorC(){
    document.getElementById("C").style.backgroundColor = "lightblue";
    sleep(3000);
}

function answerIsWrong(){
    // progress bar
    document.getElementById(currentQuestion_id).style.backgroundColor = "pink";

    // color the choice pane lightblue and sleep for 3 secs
    switch(questions[currentQuestion_id]["correct"]) {
        case document.getElementById("A").innerText:
            colorA();
            console.log("The answer was A");
            break;

        case document.getElementById("B").innerText:
            colorB();
            console.log("The answer was B");
            break;       

        case document.getElementById("C").innerText: 
            colorC();
            console.log("The answer was C");
            break;
    }
}
```

Could you read the codes and give me some more advice?
I appreciate your help.

**Comment by t-cool** [comment]
When I executed "colorA()" on Browser's console, `sleep(3000);` is executed at first, and then `document.getElementById("A").style.backgroundColor = "lightblue";` is followed.

The code is as follows:
```
function colorA(){
    document.getElementById("A").style.backgroundColor = "lightblue";
    sleep(3000);
}
```

**Comment by shahrukh170** [comment]
hello sir ,
thank you for your reply , i was busy with some domestic work , now i will
try to fix it sir dont worry , give me three hours time , if so i would be
most graeful for this regard.Thank you for your time and interest in my
work sir .
regards
shahrukh

**Comment by shahrukh170** [comment]
it changes color to red sir , its working  , the quotation marks in
document.getElementById("currentQuestion_id").style.backgroundColor =
"pink";

the fixed complete code for quizjs is given below

function colorA(){
    document.getElementById("A").style.backgroundColor = "lightblue";
    sleep(3000);
}

function colorB(){
    document.getElementById("B").style.backgroundColor = "lightblue";
    sleep(3000);
}

function colorC(){
    document.getElementById("C").style.backgroundColor = "lightblue";
    sleep(3000);
}

function answerIsWrong(){
    // progress bar
    document.getElementById("currentQuestion_id").style.backgroundColor =
"pink";

    // color the choice pane lightblue and sleep for 3 secs
    switch(questions['currentQuestion_id']["correct"]) {
        case document.getElementById("A").innerText:
            colorA();
            console.log("The answer was A");
            break;

        case document.getElementById("B").innerText:
            colorB();
            console.log("The answer was B");
            break;

        case document.getElementById("C").innerText:
            colorC();
            console.log("The answer was C");
            break;
    }
}

**Comment by t-cool** [comment]
@shahrukh170 
If we put The quotation marks there, it cannot access to the property.
In the app, "currentQuestion_id" is the id for the circles of the progress bar, and it is initialized to 0 in the code.

```
let currentQuestion_id = 0;
```

That's why `document.getElementById("currentQuestion_id")` returns `null`, and `document.getElementById(0)` returns the value.

**Comment by shahrukh170** [comment]
Hello sir ,
Can you send me full code please so that I can fix it for you ,because i am
getting "question variable is not defined ".
Regards,
Shahrukh

**Comment by t-cool** [comment]
@shahrukh170 
You can see the full code on this Github. Github is a place to share codes:
https://github.com/t-cool/nantango

**Comment by shahrukh170** [comment]
hello sir,
the code is working fine , which browser are you using ?it works fine with
chrome and firefox ? another thing , place the java script code after
</body> tag and before </html> end tag .if the problem exists i am still
here to fix it for you sir , please dont worry .
regards,
shahrukh

**Comment by t-cool** [comment]
@shahrukh170 
The problem was fixed. Thank you for taking your time.
